data:
  raw_data_path: "data/raw/NYC.csv"       
  processed_data_path: "data/processed/clean_train.csv"
  interim_data_path: "data/interim/"
model:
  output_path: "models/hist_model.pkl"
  test_size: 0.2
  random_state: 42